# Generated by Django 4.2.1 on 2023-05-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='count',
            name='lastModifie',
            field=models.CharField(default='none', max_length=150),
        ),
        migrations.AlterField(
            model_name='count',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
