# Generated by Django 4.2.1 on 2023-05-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0002_count_lastmodifie_alter_count_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
